name: CI/CD MLOps

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PROJECT_ID: ${{ secrets.PROJECT_ID }}

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests  # ✅ Testleri ekleme aşaması
        run: |
          pytest --disable-warnings --maxfail=3

      - name: Set up gcloud CLI
        uses: google-github-actions/auth@v1
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          credentials_json: ${{ secrets.CREDENTIALS_JSON }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}
          
      - name: Build the container image and push to Artifact Registry
        env:
          PROJECT_ID: ${{ secrets.PROJECT_ID }}
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev
          docker build -t us-central1-docker.pkg.dev/plucky-point-451512-u9/mlops/fastapi:latest .
          docker push us-central1-docker.pkg.dev/plucky-point-451512-u9/mlops/fastapi:latest

      - name: Deploy to Cloud Run
        env:
             PROJECT_ID: ${{ secrets.PROJECT_ID }}
             SERVICE_ACCOUNT: ${{ secrets.SERVICE_ACCOUNT }}
        run: |
          gcloud run deploy fastapi 
            --image=us-central1-docker.pkg.dev/$PROJECT_ID/mlops/fastapi:latest 
            --allow-unauthenticated 
            --port=8080 
            --service-account=$SERVICE_ACCOUNT 
            --cpu-boost 
            --region=us-central1 
            --project=$PROJECT_ID
